// ─── State-specific content for SEO and page personalization ────────────────
// Each entry gives the state page unique flavor while reusing the same template

export const STATE_DATA = {
  alabama: {
    nickname: 'The Heart of Dixie',
    blurb: 'From Birmingham backyard cookouts to Huntsville corporate events, Hibachi Connect brings live-fire teppanyaki to every corner of Alabama.',
    heroSub: 'Alabama families love bringing the hibachi experience home — lively, delicious, and completely stress-free.',
    faq: [
      { q: 'Do you serve rural areas in Alabama?', a: 'Yes — we travel throughout Alabama, including suburbs and rural communities. Travel fees may apply for locations beyond 30 miles of a major metro.' },
      { q: 'Can you handle large events in Birmingham or Huntsville?', a: 'Absolutely. We deploy multiple chef stations for 50+ guests and have served corporate events, university celebrations, and large family reunions across Alabama.' },
    ],
    coverage: 'Birmingham, Huntsville, Montgomery, Mobile, Tuscaloosa, Hoover, Auburn, Dothan',
    regionNotes: 'We serve all of Alabama including Gulf Coast communities near Mobile and university towns like Auburn and Tuscaloosa.',
  },
  arizona: {
    nickname: 'The Grand Canyon State',
    blurb: 'From Scottsdale patio parties to Phoenix corporate events, Hibachi Connect is Arizona\'s premier private hibachi chef service.',
    heroSub: 'Arizona\'s year-round outdoor lifestyle is perfect for backyard hibachi — beautiful evenings, open patios, and incredible food.',
    faq: [
      { q: 'Do you cook outdoors in Arizona\'s heat?', a: 'We do! We schedule events to maximize comfort — typically evenings in summer. Our chefs are experienced with desert climate cooking and we always bring proper ventilation equipment.' },
      { q: 'Do you serve Tucson and Flagstaff in addition to Phoenix?', a: 'Yes — we service the entire state of Arizona. Tucson, Flagstaff, Sedona, and surrounding communities are all covered. Travel fees may apply for remote areas.' },
    ],
    coverage: 'Phoenix, Scottsdale, Tempe, Mesa, Chandler, Gilbert, Glendale, Tucson, Flagstaff, Sedona, Peoria, Surprise',
    regionNotes: 'We cover all Phoenix metro neighborhoods plus southern Arizona through Tucson and northern communities including Flagstaff.',
  },
  arkansas: {
    nickname: 'The Natural State',
    blurb: 'Hibachi Connect brings the teppanyaki experience to Arkansas — from Little Rock suburbs to Fayetteville celebrations.',
    heroSub: 'Arkansas\'s love for outdoor gatherings and great food makes it the perfect setting for a live hibachi experience.',
    faq: [
      { q: 'Do you serve Northwest Arkansas (Fayetteville/Bentonville)?', a: 'Yes — Northwest Arkansas is one of our most popular regions. We regularly serve Fayetteville, Springdale, Rogers, and Bentonville.' },
      { q: 'What\'s the minimum group size in Arkansas?', a: 'Our minimum is 10 guests ($600 minimum spend). This is the same across all states including Arkansas.' },
    ],
    coverage: 'Little Rock, Fayetteville, Springdale, Fort Smith, Rogers, Bentonville, Conway, Jonesboro',
    regionNotes: 'We serve all major Arkansas metro areas including the booming Northwest Arkansas corridor.',
  },
  california: {
    nickname: 'The Golden State',
    blurb: 'From LA backyard parties to Bay Area corporate retreats, Hibachi Connect is California\'s go-to private hibachi chef service.',
    heroSub: 'California\'s culture of outdoor entertaining and world-class food makes it the ideal home for live-fire hibachi.',
    faq: [
      { q: 'Do you serve both Northern and Southern California?', a: 'Yes — we have chefs across the entire state, from San Diego and Los Angeles to San Francisco and Sacramento. Travel fees vary by region.' },
      { q: 'Can you cook on apartment or condo patios in California?', a: 'We can if there\'s adequate space (minimum 10×10 ft) and proper ventilation. Many California condo buildings have shared outdoor spaces that work well for hibachi events.' },
    ],
    coverage: 'Los Angeles, San Diego, San Francisco, San Jose, Sacramento, Fresno, Long Beach, Anaheim, Oakland, Riverside, Bakersfield, San Bernardino',
    regionNotes: 'We serve all of California\'s major metros. LA and Orange County are especially popular for backyard hibachi events.',
  },
  colorado: {
    nickname: 'The Centennial State',
    blurb: 'Hibachi Connect brings live teppanyaki to Colorado — from Denver neighborhood parties to mountain resort celebrations.',
    heroSub: 'Colorado\'s outdoor culture and love for exceptional food makes backyard hibachi an unforgettable experience year-round.',
    faq: [
      { q: 'Do you serve mountain communities like Vail or Aspen?', a: 'Yes — we serve mountain communities with advance booking. Travel fees apply for locations above 8,000 ft elevation. We\'re experienced with high-altitude cooking logistics.' },
      { q: 'Can you do winter events in Colorado?', a: 'Absolutely! We can set up in heated garages, enclosed patios, or indoor spaces. Many of our most memorable Colorado events have been cozy winter gatherings.' },
    ],
    coverage: 'Denver, Colorado Springs, Aurora, Fort Collins, Lakewood, Thornton, Arvada, Westminster, Boulder, Pueblo, Centennial, Highlands Ranch',
    regionNotes: 'We serve the entire Front Range plus mountain communities from Vail and Aspen to Steamboat Springs with advance notice.',
  },
  connecticut: {
    nickname: 'The Constitution State',
    blurb: 'From Hartford corporate events to Greenwich estate parties, Hibachi Connect brings world-class teppanyaki to Connecticut.',
    heroSub: 'Connecticut\'s vibrant community of food lovers and event hosts makes it a perfect destination for private hibachi dining.',
    faq: [
      { q: 'Do you serve smaller Connecticut towns, not just Hartford or Stamford?', a: 'Yes — we service all of Connecticut, including shoreline communities, the Farmington Valley, and Fairfield County. No city is too small.' },
      { q: 'Can you do events near the Connecticut shore?', a: 'Absolutely — shoreline properties from Westport to Mystic are a popular destination for our summer hibachi events.' },
    ],
    coverage: 'Hartford, Bridgeport, New Haven, Stamford, Waterbury, Norwalk, Danbury, New Britain, Greenwich, Milford',
    regionNotes: 'We serve all of Connecticut, from Fairfield County\'s Gold Coast to Eastern CT shoreline communities.',
  },
  delaware: {
    nickname: 'The First State',
    blurb: 'Hibachi Connect serves all of Delaware — from Wilmington corporate dinners to Rehoboth Beach summer gatherings.',
    heroSub: 'Delaware\'s close-knit communities love the intimacy and spectacle of a private hibachi dinner at home.',
    faq: [
      { q: 'Do you serve beach communities like Rehoboth or Dewey Beach?', a: 'Yes — Delaware\'s beach communities are a popular summer destination for our chefs. Book early for summer weekends as availability fills fast.' },
      { q: 'What\'s the travel range within Delaware?', a: 'We cover the entire state of Delaware with no extra travel fee. Delaware\'s compact size means we can serve New Castle, Kent, and Sussex counties equally.' },
    ],
    coverage: 'Wilmington, Dover, Newark, Middletown, Smyrna, Milford, Seaford, Rehoboth Beach, Georgetown',
    regionNotes: 'As a small state, we cover all of Delaware — no area is out of range.',
  },
  florida: {
    nickname: 'The Sunshine State',
    blurb: 'From Miami pool parties to Tampa corporate events, Hibachi Connect is Florida\'s favorite private hibachi chef service.',
    heroSub: 'Florida\'s love for outdoor entertaining and warm weather makes it perfect for a live-fire hibachi party any night of the year.',
    faq: [
      { q: 'Do you cook outside even in Florida\'s summer heat and humidity?', a: 'Yes — our chefs are trained for Florida\'s climate. We recommend evening events in summer months and always have proper equipment for humid conditions.' },
      { q: 'Do you serve both coasts — Tampa Bay and Miami/Fort Lauderdale?', a: 'Yes — we have chef teams on both coasts. East Coast (Miami, Fort Lauderdale, Palm Beach) and West Coast (Tampa, Sarasota, Naples) are both well-covered.' },
    ],
    coverage: 'Miami, Orlando, Tampa, Jacksonville, Fort Lauderdale, St. Petersburg, Tallahassee, Cape Coral, Sarasota, Naples, Boca Raton, Hialeah',
    regionNotes: 'We serve all of Florida including the Keys (with advance notice), Panhandle communities, and Central Florida suburbs.',
  },
  georgia: {
    nickname: 'The Peach State',
    blurb: 'From Atlanta\'s Buckhead estates to Savannah\'s historic squares, Hibachi Connect brings live teppanyaki to Georgia.',
    heroSub: 'Georgia\'s culture of hospitality and love for great food makes private hibachi a natural choice for events across the state.',
    faq: [
      { q: 'Do you serve Savannah and coastal Georgia?', a: 'Yes — Savannah and the Golden Isles are beautiful settings for hibachi events. We serve coastal Georgia with advance booking.' },
      { q: 'Can you set up in Atlanta-area neighborhoods with smaller yards?', a: 'Absolutely — many of our Atlanta events are in townhome communities and smaller yards. We work with your space, not against it. Minimum 10×10 ft clearance needed.' },
    ],
    coverage: 'Atlanta, Augusta, Columbus, Macon, Savannah, Athens, Sandy Springs, Roswell, Marietta, Alpharetta, Warner Robins, Albany',
    regionNotes: 'We serve Metro Atlanta and surrounding suburbs plus major Georgia cities including Savannah, Augusta, and Columbus.',
  },
  idaho: {
    nickname: 'The Gem State',
    blurb: 'Hibachi Connect brings live-fire teppanyaki to Idaho — from Boise backyard parties to Sun Valley resort events.',
    heroSub: 'Idaho\'s outdoor lifestyle and tight-knit community spirit makes private hibachi an unforgettable way to celebrate together.',
    faq: [
      { q: 'Do you serve rural areas and smaller Idaho towns?', a: 'Yes — we travel throughout Idaho. Travel fees apply for remote locations, but no community is off-limits. Twin Falls, Pocatello, and Idaho Falls are all regularly served.' },
      { q: 'Can you cook in Idaho\'s winters?', a: 'Yes — we offer indoor hibachi setups for winter months. A garage, barn, or covered patio works perfectly and creates an amazing winter event atmosphere.' },
    ],
    coverage: 'Boise, Nampa, Meridian, Idaho Falls, Pocatello, Caldwell, Twin Falls, Coeur d\'Alene',
    regionNotes: 'We serve all major Idaho cities and can travel to resort communities like Sun Valley and Coeur d\'Alene.',
  },
  illinois: {
    nickname: 'The Land of Lincoln',
    blurb: 'From Chicago rooftop parties to Springfield family celebrations, Hibachi Connect brings the hibachi experience to Illinois.',
    heroSub: 'Illinois\'s vibrant food culture and love for entertaining makes private hibachi a standout choice for any special occasion.',
    faq: [
      { q: 'Can you do rooftop or condo events in Chicago?', a: 'Yes — we have experience with Chicago\'s unique urban event spaces. Rooftops, courtyards, and private parking areas all work with our mobile setup.' },
      { q: 'Do you serve suburbs like Naperville, Schaumburg, and Evanston?', a: 'Absolutely — Chicago suburbs are some of our busiest areas. All suburban communities within 60 miles of the city are served at standard rates.' },
    ],
    coverage: 'Chicago, Aurora, Naperville, Joliet, Rockford, Springfield, Elgin, Peoria, Champaign, Waukegan, Cicero, Schaumburg',
    regionNotes: 'We serve the Chicago metro, all suburbs, and downstate Illinois cities including Springfield, Peoria, and Champaign.',
  },
  indiana: {
    nickname: 'The Hoosier State',
    blurb: 'From Indianapolis neighborhood cookouts to Fort Wayne family reunions, Hibachi Connect brings live hibachi to Indiana.',
    heroSub: 'Indiana\'s spirit of community and love for great food makes private hibachi the perfect addition to any gathering.',
    faq: [
      { q: 'Do you serve smaller Indiana cities like Muncie or Terre Haute?', a: 'Yes — we serve all of Indiana. Smaller cities may have a travel fee if outside our primary service zones, but we always try to accommodate every request.' },
      { q: 'Can you handle Speedway/race weekend events near Indianapolis?', a: 'Absolutely — race weekend events are a specialty! We book up quickly around major Indianapolis Motor Speedway events, so book 3–4 weeks in advance.' },
    ],
    coverage: 'Indianapolis, Fort Wayne, Evansville, South Bend, Carmel, Fishers, Bloomington, Hammond, Lafayette, Muncie',
    regionNotes: 'We cover all of Indiana from the Gary/Hammond area near Chicago to Evansville in the south.',
  },
  iowa: {
    nickname: 'The Hawkeye State',
    blurb: 'Hibachi Connect brings live teppanyaki dining to Iowa — from Des Moines suburban parties to Iowa City celebrations.',
    heroSub: 'Iowa\'s warm community spirit and love for home entertaining makes private hibachi a uniquely memorable experience.',
    faq: [
      { q: 'Do you serve college towns like Iowa City and Ames?', a: 'Yes — college town events are some of our favorites! Iowa City and Ames have vibrant event cultures and we serve both regularly.' },
      { q: 'What\'s the farthest west in Iowa you travel?', a: 'We cover all of Iowa including Council Bluffs and the Missouri border. No area of Iowa is outside our service range.' },
    ],
    coverage: 'Des Moines, Cedar Rapids, Davenport, Sioux City, Iowa City, Waterloo, Ames, Council Bluffs',
    regionNotes: 'We serve Iowa statewide, from the Quad Cities in the east to Sioux City in the west.',
  },
  kansas: {
    nickname: 'The Sunflower State',
    blurb: 'From Wichita backyard gatherings to Kansas City-area corporate events, Hibachi Connect serves all of Kansas.',
    heroSub: 'Kansas hosts some of the most welcoming communities in America — and a private hibachi party is the perfect way to celebrate together.',
    faq: [
      { q: 'Do you serve the Kansas side of the Kansas City metro?', a: 'Yes — we serve both sides of the KC metro including Overland Park, Lenexa, Olathe, and Shawnee. No extra fee within the metro area.' },
      { q: 'Do you travel to rural Kansas communities?', a: 'We do with advance planning. Travel fees apply for locations 30+ miles from Wichita or Kansas City, but we love serving rural Kansas events.' },
    ],
    coverage: 'Wichita, Overland Park, Kansas City (KS), Olathe, Topeka, Lawrence, Shawnee, Manhattan, Lenexa',
    regionNotes: 'We cover Kansas statewide including the KC metro border communities and college towns like Lawrence and Manhattan.',
  },
  kentucky: {
    nickname: 'The Bluegrass State',
    blurb: 'From Louisville Derby parties to Lexington horse farm celebrations, Hibachi Connect brings live hibachi to Kentucky.',
    heroSub: 'Kentucky\'s tradition of fine dining and lavish entertaining makes private hibachi a perfect match for any Kentucky gathering.',
    faq: [
      { q: 'Do you do Derby week events in Louisville?', a: 'Kentucky Derby week is one of our most popular booking seasons! Reserve 6–8 weeks in advance for Derby weekend. We handle private pre-race dinners and post-race celebrations.' },
      { q: 'Do you serve Northern Kentucky (Cincinnati area)?', a: 'Yes — we serve the entire Northern Kentucky area including Covington, Newport, and Florence, which is part of the Greater Cincinnati metro.' },
    ],
    coverage: 'Louisville, Lexington, Bowling Green, Owensboro, Covington, Richmond, Florence, Georgetown, Henderson',
    regionNotes: 'We serve all of Kentucky from Northern KY on the Ohio border to Paducah in the west.',
  },
  louisiana: {
    nickname: 'The Pelican State',
    blurb: 'Louisiana already knows good food — and Hibachi Connect brings a whole new level of live-fire cooking to the Bayou State.',
    heroSub: 'In a state famous for culinary culture, private hibachi is the perfect showstopper for your next Louisiana celebration.',
    faq: [
      { q: 'Can you cook during Mardi Gras season?', a: 'Yes — Mardi Gras is one of our busiest times in Louisiana. We serve pre-parade gatherings, krewe parties, and post-Mardi Gras celebrations. Book early!' },
      { q: 'Do you work in New Orleans\' unique event spaces (courtyards, etc.)?', a: 'We specialize in adaptable setups. New Orleans courtyards, balconies, and private event spaces are some of our favorite venues — just ensure at least 10×10 ft clearance.' },
    ],
    coverage: 'New Orleans, Baton Rouge, Shreveport, Metairie, Lafayette, Lake Charles, Kenner, Bossier City',
    regionNotes: 'We serve all of Louisiana including bayou communities, the Cajun Country corridor, and North Louisiana.',
  },
  maine: {
    nickname: 'The Pine Tree State',
    blurb: 'Hibachi Connect brings live teppanyaki to Maine — from Portland waterfront parties to lake house summer celebrations.',
    heroSub: 'Maine\'s stunning scenery and love of outdoor living makes it a magical setting for a live-fire hibachi experience.',
    faq: [
      { q: 'Do you serve coastal Maine communities?', a: 'Yes — coastal Maine communities from Kittery to Bar Harbor are all reachable. Summer is our peak season for coastal events, so book 4+ weeks ahead.' },
      { q: 'Can you cook at lake house properties?', a: 'Absolutely — lake house hibachi events are some of the most memorable we do. A dock-side or deck setup with hibachi is an unforgettable Maine experience.' },
    ],
    coverage: 'Portland, Lewiston, Bangor, South Portland, Auburn, Biddeford, Brunswick, Saco',
    regionNotes: 'We serve Southern and Central Maine most frequently, with extended travel to Downeast Maine and the North Woods region.',
  },
  maryland: {
    nickname: 'The Old Line State',
    blurb: 'From Baltimore waterfront events to Annapolis celebrations, Hibachi Connect serves Maryland with top-tier private hibachi.',
    heroSub: 'Maryland\'s blend of mid-Atlantic culture and Chesapeake Bay tradition makes private hibachi an inspired choice for any special event.',
    faq: [
      { q: 'Do you serve the Maryland suburbs of Washington, DC?', a: 'Yes — Montgomery County, Prince George\'s County, and all DC-adjacent Maryland suburbs are fully served. These are some of our busiest service areas.' },
      { q: 'Can you do events with seafood focus in Maryland?', a: 'Absolutely — Maryland crab and seafood-forward hibachi is one of our most requested packages. We can incorporate local seafood into your custom menu.' },
    ],
    coverage: 'Baltimore, Frederick, Rockville, Gaithersburg, Bowie, Hagerstown, Annapolis, College Park, Towson',
    regionNotes: 'We serve all of Maryland including DC suburbs, Baltimore City & County, and Eastern Shore communities.',
  },
  massachusetts: {
    nickname: 'The Bay State',
    blurb: 'From Boston suburbs to Cape Cod summer parties, Hibachi Connect brings live teppanyaki to Massachusetts.',
    heroSub: 'Massachusetts\'s rich food culture and year-round event scene makes private hibachi an exciting addition to any gathering.',
    faq: [
      { q: 'Do you serve Cape Cod and the Islands?', a: 'We serve Cape Cod and can travel to Martha\'s Vineyard and Nantucket with advance notice and ferry logistics planning. Summer bookings fill quickly — reserve early.' },
      { q: 'Can you set up in Boston-area homes with smaller outdoor spaces?', a: 'Yes — we\'re experienced with Boston\'s urban spaces. Triple-deckers with decks, courtyard brownstones, and rooftop spaces all work with our compact setup.' },
    ],
    coverage: 'Boston, Worcester, Springfield, Lowell, Cambridge, New Bedford, Brockton, Quincy, Lynn, Fall River',
    regionNotes: 'We cover all of Massachusetts from Greater Boston to Western MA and the Cape & Islands region.',
  },
  michigan: {
    nickname: 'The Great Lakes State',
    blurb: 'From Detroit metro events to lakehouse gatherings in Northern Michigan, Hibachi Connect serves all of Michigan.',
    heroSub: 'Michigan\'s beautiful outdoor spaces and love for great food make private hibachi a highlight of any summer or year-round gathering.',
    faq: [
      { q: 'Do you serve Upper Peninsula Michigan?', a: 'We serve the Lower Peninsula and border UP communities. For deep UP locations, please contact us for custom travel arrangements.' },
      { q: 'Can you do events on Michigan lake properties?', a: 'Absolutely — lakehouse hibachi events are incredibly popular in Michigan. Dock-side or beach setups create unforgettable experiences.' },
    ],
    coverage: 'Detroit, Grand Rapids, Warren, Sterling Heights, Ann Arbor, Lansing, Flint, Dearborn, Livonia, Troy',
    regionNotes: 'We serve the entire Lower Peninsula of Michigan, from metro Detroit to Traverse City and the Thumb.',
  },
  minnesota: {
    nickname: 'The Land of 10,000 Lakes',
    blurb: 'From Twin Cities suburban parties to lake cabin celebrations, Hibachi Connect brings live hibachi to Minnesota.',
    heroSub: 'Minnesotans love great food and lake country living — and a private hibachi party is the ultimate way to celebrate both.',
    faq: [
      { q: 'Do you cook outdoors in Minnesota winters?', a: 'For winter events, we recommend indoor setups: a large garage, barn, or heated tent works perfectly. We\'ve done incredible Minnesota winter hibachi events.' },
      { q: 'Do you serve lake communities outside the Twin Cities?', a: 'Yes — lake community events are popular in summer months. We travel to Brainerd, Alexandria, and other lake regions with advance booking.' },
    ],
    coverage: 'Minneapolis, Saint Paul, Rochester, Duluth, Brooklyn Park, Plymouth, Maple Grove, Woodbury, Bloomington',
    regionNotes: 'We serve the Twin Cities metro and surrounding suburbs plus popular lake destinations with seasonal availability.',
  },
  mississippi: {
    nickname: 'The Magnolia State',
    blurb: 'Hibachi Connect brings live teppanyaki to Mississippi — from Jackson family celebrations to Gulf Coast resort events.',
    heroSub: 'Mississippi\'s legendary Southern hospitality and love for communal dining makes private hibachi a natural fit.',
    faq: [
      { q: 'Do you serve Gulf Coast communities like Biloxi and Gulfport?', a: 'Yes — the Gulf Coast is a popular destination for our chefs. Casino resort areas, beach properties, and Gulf Coast communities are all served.' },
      { q: 'What\'s the minimum group size in Mississippi?', a: 'Our standard minimum is 10 guests ($600 minimum spend). This applies statewide, including Mississippi.' },
    ],
    coverage: 'Jackson, Gulfport, Southaven, Hattiesburg, Biloxi, Meridian, Tupelo, Olive Branch',
    regionNotes: 'We serve all of Mississippi from the Tennessee border communities in the north to the Gulf Coast in the south.',
  },
  missouri: {
    nickname: 'The Show-Me State',
    blurb: 'From St. Louis rooftop parties to Kansas City corporate events, Hibachi Connect serves Missouri statewide.',
    heroSub: 'Missouri\'s central location and vibrant food scene makes it a hub for exceptional private dining experiences like hibachi.',
    faq: [
      { q: 'Do you serve both Kansas City and St. Louis?', a: 'Yes — we have chef teams in both major metro areas. Kansas City and St. Louis events are both served at standard rates with no extra travel fee within city limits.' },
      { q: 'Can you handle Branson-area resort events?', a: 'Absolutely — Branson resort events are some of our most spectacular. We handle everything from lakeside mansion parties to private event spaces at area resorts.' },
    ],
    coverage: 'Kansas City, St. Louis, Springfield, Columbia, Independence, Lee\'s Summit, O\'Fallon, St. Joseph, St. Charles',
    regionNotes: 'We serve all of Missouri including the Ozarks, Branson resort area, and communities along the Mississippi River.',
  },
  montana: {
    nickname: 'Big Sky Country',
    blurb: 'Hibachi Connect brings live teppanyaki to Montana — from Billings backyard parties to Whitefish mountain celebrations.',
    heroSub: 'Montana\'s breathtaking landscapes and outdoor spirit create an unforgettable backdrop for a live-fire hibachi experience.',
    faq: [
      { q: 'Do you travel to remote Montana locations?', a: 'We serve all major Montana cities and can travel to rural areas with advance planning. Additional travel fees apply for remote locations more than 50 miles from Billings, Missoula, or Bozeman.' },
      { q: 'Can you set up events near Glacier or Yellowstone?', a: 'Yes — we can serve communities near both national parks with advance planning. Gateway towns like West Glacier and Gardiner are within range.' },
    ],
    coverage: 'Billings, Missoula, Great Falls, Bozeman, Butte, Helena, Kalispell, Whitefish',
    regionNotes: 'We serve all major Montana metro areas and can travel to resort and gateway communities with advance notice.',
  },
  nebraska: {
    nickname: 'The Cornhusker State',
    blurb: 'From Omaha neighborhood cookouts to Lincoln Husker celebrations, Hibachi Connect serves all of Nebraska.',
    heroSub: 'Nebraska\'s community-first culture and love for backyard gatherings makes private hibachi a natural fit for any occasion.',
    faq: [
      { q: 'Do you serve Western Nebraska?', a: 'We serve all of Nebraska including the Panhandle. Travel fees apply for locations beyond 50 miles of Omaha or Lincoln.' },
      { q: 'Can you do game day events in Lincoln during Husker football season?', a: 'Yes — game day hibachi events are very popular in Lincoln! We handle pre-game and post-game gatherings throughout the Husker season.' },
    ],
    coverage: 'Omaha, Lincoln, Bellevue, Grand Island, Kearney, Fremont, Hastings, North Platte',
    regionNotes: 'We serve the Omaha-Lincoln corridor and all major Nebraska communities statewide.',
  },
  nevada: {
    nickname: 'The Silver State',
    blurb: 'From Las Vegas backyard parties to Reno tech events, Hibachi Connect brings the hibachi experience to Nevada.',
    heroSub: 'Nevada knows how to throw a party — and a private hibachi chef brings Vegas-level entertainment to your own backyard.',
    faq: [
      { q: 'Can you set up in Las Vegas with limited outdoor space?', a: 'Yes — Las Vegas has many private courtyards, pool decks, and resort spaces that work perfectly. We\'re experienced with urban Nevada event logistics.' },
      { q: 'Do you serve Reno and Northern Nevada?', a: 'Yes — Reno, Sparks, and Northern Nevada communities are well-served. We have chef teams in both Southern and Northern Nevada.' },
    ],
    coverage: 'Las Vegas, Henderson, Reno, North Las Vegas, Sparks, Carson City, Boulder City, Mesquite',
    regionNotes: 'We serve both Southern Nevada (Las Vegas metro) and Northern Nevada (Reno/Sparks area) with teams in each region.',
  },
  'new-hampshire': {
    nickname: 'The Granite State',
    blurb: 'Hibachi Connect brings live teppanyaki to New Hampshire — from Manchester gatherings to Lake Winnipesaukee summer celebrations.',
    heroSub: 'New Hampshire\'s outdoor culture and New England love for exceptional dining makes private hibachi a memorable experience.',
    faq: [
      { q: 'Do you serve Lake Winnipesaukee and Lakes Region communities?', a: 'Yes — the Lakes Region is a popular destination for summer hibachi events. Meredith, Laconia, Wolfeboro, and surrounding communities are all reachable.' },
      { q: 'Do you travel to the White Mountains area?', a: 'We can reach White Mountains gateway communities like North Conway and Lincoln with advance booking. Travel fees apply.' },
    ],
    coverage: 'Manchester, Nashua, Concord, Derry, Dover, Rochester, Salem, Merrimack, Londonderry',
    regionNotes: 'We serve Southern NH most frequently and extend to Lakes Region and White Mountains with advance planning.',
  },
  'new-jersey': {
    nickname: 'The Garden State',
    blurb: 'From Jersey Shore summer parties to North Jersey corporate events, Hibachi Connect serves all of New Jersey.',
    heroSub: 'New Jersey\'s vibrant communities and love for backyard entertaining makes private hibachi the perfect addition to any gathering.',
    faq: [
      { q: 'Do you serve the Jersey Shore communities?', a: 'Yes — Shore communities from Sandy Hook to Cape May are popular summer destinations for our chefs. Book 4–6 weeks ahead for summer shore events.' },
      { q: 'Can you set up in suburban NJ homes near NYC?', a: 'Absolutely — North and Central NJ suburbs are some of our most active service areas. Bergen, Essex, Union, and Middlesex counties are all well-covered.' },
    ],
    coverage: 'Newark, Jersey City, Paterson, Elizabeth, Trenton, Camden, Woodbridge, Hamilton, Toms River, Clifton',
    regionNotes: 'We serve all of New Jersey from the NYC suburbs in the north to Cape May in the south, including all Shore communities.',
  },
  'new-mexico': {
    nickname: 'The Land of Enchantment',
    blurb: 'Hibachi Connect brings live-fire teppanyaki to New Mexico — from Albuquerque neighborhood parties to Santa Fe art colony events.',
    heroSub: 'New Mexico\'s outdoor culture and love of spectacular food and entertainment makes private hibachi an inspired choice.',
    faq: [
      { q: 'Do you serve Santa Fe and Taos?', a: 'Yes — Santa Fe and Taos are popular destinations for our chefs. The arts community and resort scene in Northern New Mexico creates exceptional event opportunities.' },
      { q: 'Can you cook outdoors during New Mexico\'s high desert weather?', a: 'Absolutely — New Mexico\'s climate is excellent for outdoor events much of the year. We advise on best seasonal timing and always bring appropriate equipment for desert conditions.' },
    ],
    coverage: 'Albuquerque, Las Cruces, Rio Rancho, Santa Fe, Roswell, Farmington, Taos, Hobbs',
    regionNotes: 'We serve all of New Mexico including Northern NM resort communities and Southern NM border cities.',
  },
  'new-york': {
    nickname: 'The Empire State',
    blurb: 'From Long Island estate parties to Upstate New York lake celebrations, Hibachi Connect brings world-class hibachi to New York.',
    heroSub: 'New York\'s world-class food culture and vibrant event scene makes private hibachi a standout choice for any celebration.',
    faq: [
      { q: 'Do you serve Long Island and Westchester?', a: 'Yes — Long Island (Nassau and Suffolk Counties) and Westchester are among our most active New York service areas. No extra travel fee within these regions.' },
      { q: 'Do you serve Upstate New York cities like Buffalo and Albany?', a: 'Yes — Upstate NY is fully served including Buffalo, Albany, Rochester, and Syracuse. We have regional chef teams throughout the state.' },
    ],
    coverage: 'New York City, Buffalo, Rochester, Yonkers, Syracuse, Albany, New Rochelle, Mount Vernon, Schenectady, Utica',
    regionNotes: 'We serve all of New York State including NYC metro, Long Island, Westchester, and all major Upstate cities.',
  },
  'north-carolina': {
    nickname: 'The Tar Heel State',
    blurb: 'From Charlotte backyard parties to Raleigh corporate retreats, Hibachi Connect is North Carolina\'s premier private hibachi service.',
    heroSub: 'North Carolina\'s booming cities and outdoor lifestyle make it a perfect home for live-fire hibachi events year-round.',
    faq: [
      { q: 'Do you serve the Research Triangle (Raleigh, Durham, Chapel Hill)?', a: 'Yes — the Triangle is one of our most active North Carolina markets. Raleigh, Durham, Cary, and Chapel Hill are all served at standard rates.' },
      { q: 'Do you serve Asheville and the Western NC mountains?', a: 'Yes — Asheville and surrounding mountain communities are a popular destination. Reserve 3–4 weeks ahead for mountain area events.' },
    ],
    coverage: 'Charlotte, Raleigh, Greensboro, Durham, Winston-Salem, Fayetteville, Cary, Wilmington, High Point, Asheville',
    regionNotes: 'We serve all of North Carolina from the Research Triangle to the Charlotte metro, Coastal Plain, and Western Mountains.',
  },
  'north-dakota': {
    nickname: 'The Peace Garden State',
    blurb: 'Hibachi Connect brings live teppanyaki to North Dakota — from Fargo suburban events to Bismarck family celebrations.',
    heroSub: 'North Dakota\'s tight-knit communities and love for home gatherings makes private hibachi an especially memorable experience.',
    faq: [
      { q: 'Can you cook outdoors during North Dakota winters?', a: 'For winter events, we strongly recommend indoor setups. A spacious garage, heated barn, or event venue works great and keeps everyone comfortable.' },
      { q: 'Do you serve smaller North Dakota communities?', a: 'Yes — we serve communities across North Dakota. Travel fees apply for locations more than 50 miles from Fargo or Bismarck.' },
    ],
    coverage: 'Fargo, Bismarck, Grand Forks, Minot, West Fargo, Mandan, Dickinson, Jamestown',
    regionNotes: 'We serve all major North Dakota cities with primary chef teams based in Fargo and Bismarck.',
  },
  ohio: {
    nickname: 'The Buckeye State',
    blurb: 'From Columbus neighborhood cookouts to Cleveland corporate events, Hibachi Connect serves all of Ohio.',
    heroSub: 'Ohio\'s welcoming communities and love for backyard gatherings makes private hibachi a natural choice for any occasion.',
    faq: [
      { q: 'Do you serve all three major Ohio metros — Columbus, Cleveland, and Cincinnati?', a: 'Yes — we have chef teams in all three metros. Columbus, Cleveland, and Cincinnati are all served at standard rates with no extra travel fee within city limits.' },
      { q: 'Can you serve smaller Ohio cities like Dayton, Toledo, or Akron?', a: 'Absolutely — all major Ohio cities including Dayton, Toledo, Akron, and Canton are served regularly.' },
    ],
    coverage: 'Columbus, Cleveland, Cincinnati, Toledo, Akron, Dayton, Parma, Canton, Youngstown, Lorain',
    regionNotes: 'We serve all of Ohio statewide, including all major metros and surrounding suburbs.',
  },
  oklahoma: {
    nickname: 'The Sooner State',
    blurb: 'From OKC backyard celebrations to Tulsa corporate gatherings, Hibachi Connect brings live hibachi to Oklahoma.',
    heroSub: 'Oklahoma\'s outdoor spirit and community pride makes private hibachi a perfect way to bring people together for any occasion.',
    faq: [
      { q: 'Do you serve both Oklahoma City and Tulsa?', a: 'Yes — we have chef teams in both metros. OKC and Tulsa are served at standard rates. Both cities and their suburbs are our primary Oklahoma service areas.' },
      { q: 'Do you travel to rural Oklahoma communities?', a: 'We can travel throughout Oklahoma with advance planning. Travel fees apply for remote locations more than 40 miles from OKC or Tulsa.' },
    ],
    coverage: 'Oklahoma City, Tulsa, Norman, Broken Arrow, Edmond, Lawton, Moore, Midwest City, Enid',
    regionNotes: 'We serve the OKC and Tulsa metros and all surrounding suburbs, plus major Oklahoma communities statewide.',
  },
  oregon: {
    nickname: 'The Beaver State',
    blurb: 'From Portland backyard farm-to-table events to Eugene outdoor celebrations, Hibachi Connect serves Oregon statewide.',
    heroSub: 'Oregon\'s outdoor culture and passion for exceptional, fresh food makes private hibachi a perfect fit for the Pacific Northwest lifestyle.',
    faq: [
      { q: 'Can you incorporate local Pacific Northwest ingredients into the menu?', a: 'Yes — we love working with Oregon\'s incredible local seafood, produce, and Wagyu beef. Ask about our PNW-inspired menu add-ons.' },
      { q: 'Do you serve Bend and Central Oregon?', a: 'Yes — Bend is one of Oregon\'s fastest-growing event markets for us. We serve Bend, Redmond, and Central Oregon regularly.' },
    ],
    coverage: 'Portland, Eugene, Salem, Gresham, Hillsboro, Beaverton, Bend, Medford, Springfield, Corvallis',
    regionNotes: 'We serve the Portland metro, Willamette Valley, Southern Oregon, and Central Oregon\'s high desert communities.',
  },
  pennsylvania: {
    nickname: 'The Keystone State',
    blurb: 'From Philadelphia suburbs to Pittsburgh riverfront events, Hibachi Connect serves all of Pennsylvania.',
    heroSub: 'Pennsylvania\'s rich community culture and passion for great food makes private hibachi an exceptional choice for any event.',
    faq: [
      { q: 'Do you serve both Philadelphia and Pittsburgh areas?', a: 'Yes — we have chef teams in both cities. Philadelphia suburbs (Main Line, South Jersey border) and Pittsburgh metro are both fully served.' },
      { q: 'Can you do events in Pennsylvania Dutch Country or the Pocono Mountains?', a: 'Absolutely — Lancaster County and the Poconos are popular for our resort-style hibachi events. Book 4+ weeks ahead for mountain and rural PA events.' },
    ],
    coverage: 'Philadelphia, Pittsburgh, Allentown, Erie, Reading, Scranton, Bethlehem, Lancaster, Harrisburg, York',
    regionNotes: 'We serve all of Pennsylvania from Philly to Pittsburgh and everywhere between, including rural and mountain communities.',
  },
  'rhode-island': {
    nickname: 'The Ocean State',
    blurb: 'Hibachi Connect brings live teppanyaki to Rhode Island — from Providence neighborhood events to Newport waterfront celebrations.',
    heroSub: 'Rhode Island\'s love for local food culture and coastal entertaining makes private hibachi a natural choice for any special occasion.',
    faq: [
      { q: 'Do you serve Newport and coastal Rhode Island communities?', a: 'Yes — Newport events are some of our most spectacular. Waterfront properties, mansion lawns, and harbor-side venues create amazing settings for hibachi.' },
      { q: 'Is Rhode Island\'s size a problem? Do all areas get covered?', a: 'Rhode Island\'s compact size means every part of the state is reachable at standard rates. No location in RI is beyond our service area.' },
    ],
    coverage: 'Providence, Warwick, Cranston, Pawtucket, East Providence, Woonsocket, Coventry, North Providence, Newport',
    regionNotes: 'We serve all of Rhode Island — the state\'s small size means every community is covered at no extra travel fee.',
  },
  'south-carolina': {
    nickname: 'The Palmetto State',
    blurb: 'From Charleston historic district events to Myrtle Beach celebrations, Hibachi Connect serves South Carolina statewide.',
    heroSub: 'South Carolina\'s warm climate and Southern hospitality make it an ideal setting for outdoor private hibachi events year-round.',
    faq: [
      { q: 'Do you serve Hilton Head and the Lowcountry?', a: 'Yes — Hilton Head, Beaufort, and the Lowcountry are popular destinations. Plantation communities and resort properties create stunning settings for hibachi.' },
      { q: 'Can you cook on outdoor patios in South Carolina\'s humid summers?', a: 'Absolutely — our chefs are trained for Southern humidity. We recommend evening events in peak summer and always bring proper equipment for warm-weather cooking.' },
    ],
    coverage: 'Columbia, Charleston, North Charleston, Greenville, Rock Hill, Summerville, Mount Pleasant, Spartanburg, Myrtle Beach',
    regionNotes: 'We serve all of South Carolina from Upstate (Greenville/Spartanburg) to the Lowcountry coast and Myrtle Beach.',
  },
  'south-dakota': {
    nickname: 'The Mount Rushmore State',
    blurb: 'Hibachi Connect brings live teppanyaki to South Dakota — from Sioux Falls suburban events to Black Hills celebrations.',
    heroSub: 'South Dakota\'s community spirit and stunning outdoor settings make private hibachi a uniquely memorable experience.',
    faq: [
      { q: 'Do you serve the Black Hills area and Rapid City?', a: 'Yes — Rapid City and the Black Hills region are reachable. We serve year-round with advance planning. Summer and Sturgis rally season are especially popular.' },
      { q: 'Can you handle larger events in Sioux Falls?', a: 'Absolutely — Sioux Falls is our primary South Dakota market and we regularly handle large events (50–200+ guests) in the city.' },
    ],
    coverage: 'Sioux Falls, Rapid City, Aberdeen, Brookings, Watertown, Mitchell, Yankton',
    regionNotes: 'We serve all of South Dakota, with primary coverage in Sioux Falls and Rapid City, extending to the Black Hills region.',
  },
  tennessee: {
    nickname: 'The Volunteer State',
    blurb: 'From Nashville bachelorette parties to Memphis corporate events, Hibachi Connect is Tennessee\'s favorite private hibachi service.',
    heroSub: 'Tennessee knows how to celebrate — and private hibachi is the ultimate way to bring live entertainment and incredible food to any event.',
    faq: [
      { q: 'Do you serve the Nashville bachelorette party market?', a: 'Absolutely — Nashville bachelorette and bachelor events are one of our specialties! In-home hibachi before a night out is a hugely popular Nashville experience.' },
      { q: 'Do you serve Eastern Tennessee (Knoxville, Chattanooga)?', a: 'Yes — both Knoxville and Chattanooga are well-served. We have chef teams in East, Middle, and West Tennessee.' },
    ],
    coverage: 'Nashville, Memphis, Knoxville, Chattanooga, Clarksville, Murfreesboro, Franklin, Jackson, Johnson City',
    regionNotes: 'We serve all of Tennessee from Memphis in the west to Johnson City in the east, with strong coverage in the Nashville metro.',
  },
  texas: {
    nickname: 'The Lone Star State',
    blurb: 'From Houston pool parties to Dallas corporate retreats, Hibachi Connect is Texas\'s premier private hibachi chef service — serving every corner of the Lone Star State.',
    heroSub: 'Texans know how to do things big — and a private hibachi party is the ultimate way to celebrate with family, friends, and colleagues.',
    faq: [
      { q: 'Do you serve smaller Texas cities and suburbs?', a: 'Yes — we have chef teams spread across Texas. Whether you\'re in Frisco, Pearland, Round Rock, or Allen, we\'ve got you covered at standard rates.' },
      { q: 'Can you handle very large Texas events (100+ guests)?', a: 'Absolutely — large events are our specialty. We deploy multiple chef stations for 100+ guest events and have handled corporate retreats with 300+ attendees in Texas.' },
    ],
    coverage: 'Houston, San Antonio, Dallas, Austin, Fort Worth, El Paso, Arlington, Corpus Christi, Plano, Frisco, McKinney, The Woodlands, Sugar Land, Katy, Round Rock',
    regionNotes: 'We serve all major Texas metros plus suburbs. DFW, Houston, and San Antonio have the highest chef availability.',
  },
  utah: {
    nickname: 'The Beehive State',
    blurb: 'From Salt Lake City neighborhood events to Park City resort celebrations, Hibachi Connect brings live hibachi to Utah.',
    heroSub: 'Utah\'s outdoor lifestyle and strong community culture makes private hibachi an exciting way to bring people together.',
    faq: [
      { q: 'Do you serve Park City and ski resort communities?', a: 'Yes — Park City, Deer Valley, and Snowbird area communities are popular destinations for our chefs, especially during ski season and summer resort events.' },
      { q: 'Do you travel to Southern Utah (St. George, Moab)?', a: 'Yes — Southern Utah is reachable with advance planning. Travel fees apply for locations more than 50 miles from Salt Lake City.' },
    ],
    coverage: 'Salt Lake City, West Valley City, Provo, West Jordan, Orem, Sandy, Ogden, St. George, Layton, Park City',
    regionNotes: 'We serve the Wasatch Front metro and extend to resort communities and Southern Utah with advance booking.',
  },
  vermont: {
    nickname: 'The Green Mountain State',
    blurb: 'Hibachi Connect brings live teppanyaki to Vermont — from Burlington lakeside events to ski resort celebrations in the Green Mountains.',
    heroSub: 'Vermont\'s stunning scenery and culture of food and community makes private hibachi a uniquely memorable experience.',
    faq: [
      { q: 'Do you serve ski resort communities like Stowe and Killington?', a: 'Yes — ski resort communities are a popular winter destination for our chefs. Cozy indoor hibachi at a chalet or lodge is an amazing Vermont experience.' },
      { q: 'Do you serve rural Vermont farms and event venues?', a: 'Absolutely — Vermont\'s beautiful farm venues and barn event spaces are some of our favorite settings for hibachi. Call us for rural property inquiries.' },
    ],
    coverage: 'Burlington, South Burlington, Rutland, Barre, Montpelier, St. Johnsbury, Brattleboro, Stowe',
    regionNotes: 'We serve all of Vermont from Burlington and the Champlain Valley to the Northeast Kingdom and resort communities.',
  },
  virginia: {
    nickname: 'The Old Dominion State',
    blurb: 'From Northern Virginia corporate events to Virginia Beach celebrations, Hibachi Connect serves all of Virginia.',
    heroSub: 'Virginia\'s blend of historic tradition and modern vibrancy makes private hibachi an inspired choice for any special event.',
    faq: [
      { q: 'Do you serve Northern Virginia and the DC suburbs?', a: 'Yes — Northern Virginia is one of our most active markets. Arlington, Alexandria, Fairfax, Tysons, and Reston are all fully covered at standard rates.' },
      { q: 'Do you serve Virginia Beach and Hampton Roads?', a: 'Yes — the Hampton Roads area including Virginia Beach, Norfolk, Chesapeake, and Newport News is well-served by our coastal Virginia chef team.' },
    ],
    coverage: 'Virginia Beach, Norfolk, Chesapeake, Arlington, Alexandria, Richmond, Newport News, Hampton, Roanoke, Lynchburg',
    regionNotes: 'We serve all of Virginia from NoVA and DC suburbs to Hampton Roads, Richmond, and Western Virginia.',
  },
  washington: {
    nickname: 'The Evergreen State',
    blurb: 'From Seattle backyard events to Spokane community celebrations, Hibachi Connect brings live teppanyaki to Washington State.',
    heroSub: 'Washington\'s passion for local food and outdoor living makes private hibachi a perfect match for the Pacific Northwest lifestyle.',
    faq: [
      { q: 'Can you incorporate Pacific Northwest seafood into the hibachi menu?', a: 'Yes — Washington\'s incredible local salmon, halibut, and Dungeness crab can all be incorporated into your custom hibachi menu.' },
      { q: 'Do you serve Eastern Washington (Spokane, Tri-Cities)?', a: 'Yes — Eastern Washington is fully served. Spokane and the Tri-Cities area have high demand for private hibachi events.' },
    ],
    coverage: 'Seattle, Spokane, Tacoma, Vancouver, Bellevue, Kirkland, Redmond, Renton, Everett, Kent, Federal Way',
    regionNotes: 'We serve the entire state of Washington including Western WA (Seattle metro) and Eastern WA (Spokane/Tri-Cities).',
  },
  'west-virginia': {
    nickname: 'The Mountain State',
    blurb: 'Hibachi Connect brings live teppanyaki to West Virginia — from Charleston valley events to mountain retreat celebrations.',
    heroSub: 'West Virginia\'s stunning mountain landscapes and close-knit communities create a memorable backdrop for private hibachi.',
    faq: [
      { q: 'Do you travel to mountain resort communities?', a: 'Yes — we can reach resort communities like Snowshoe and Canaan Valley with advance planning. Mountain event settings make for exceptional hibachi experiences.' },
      { q: 'What cities do you primarily serve in West Virginia?', a: 'Our primary West Virginia coverage includes Charleston, Huntington, Morgantown, Parkersburg, and Wheeling. We extend to surrounding communities from these bases.' },
    ],
    coverage: 'Charleston, Huntington, Morgantown, Parkersburg, Wheeling, Fairmont, Beckley, Clarksburg',
    regionNotes: 'We serve major West Virginia cities and can travel to resort and rural communities with advance planning.',
  },
  wisconsin: {
    nickname: 'The Badger State',
    blurb: 'From Milwaukee lakefront events to Madison Badger celebrations, Hibachi Connect serves all of Wisconsin.',
    heroSub: 'Wisconsin\'s love for community, outdoor events, and great food makes private hibachi a perfect fit for any occasion.',
    faq: [
      { q: 'Do you serve Wisconsin Dells and resort lake communities?', a: 'Yes — Wisconsin Dells and lake communities (Lake Geneva, Minocqua, etc.) are popular destinations, especially in summer. Book early for peak lake season.' },
      { q: 'Can you do events during Packers season in Green Bay?', a: 'Game day hibachi events are hugely popular in Green Bay! We handle pre-game parties and tailgate-style events throughout the NFL season.' },
    ],
    coverage: 'Milwaukee, Madison, Green Bay, Kenosha, Racine, Appleton, Waukesha, Oshkosh, Eau Claire',
    regionNotes: 'We serve all of Wisconsin from the Illinois border up through the Fox Valley and into Northern Wisconsin lake country.',
  },
  wyoming: {
    nickname: 'The Equality State',
    blurb: 'Hibachi Connect brings live teppanyaki to Wyoming — from Cheyenne community events to Jackson Hole resort celebrations.',
    heroSub: 'Wyoming\'s wide-open spaces and outdoor spirit create a spectacular setting for a live-fire hibachi experience.',
    faq: [
      { q: 'Do you serve Jackson Hole and Yellowstone gateway communities?', a: 'Yes — Jackson Hole is a popular destination for our chefs. Resort property events, dude ranch celebrations, and mountain gatherings are a specialty.' },
      { q: 'Can you travel across Wyoming\'s large distances?', a: 'Yes — Wyoming\'s geography requires advance planning for remote locations. Travel fees apply for locations more than 60 miles from Cheyenne or Casper.' },
    ],
    coverage: 'Cheyenne, Casper, Laramie, Gillette, Rock Springs, Sheridan, Jackson, Cody',
    regionNotes: 'We serve all major Wyoming communities with particular popularity in the Jackson Hole resort area.',
  },
}

// Fallback data for states not explicitly defined
export function getStateData(slug) {
  return STATE_DATA[slug] || {
    nickname: 'A Great State for Hibachi',
    blurb: `Hibachi Connect brings professional live-fire teppanyaki dining to every corner of this state — your backyard, your rules.`,
    heroSub: 'Our private hibachi chefs bring the grill, the ingredients, and the full entertainment experience directly to your home or venue.',
    faq: [
      { q: 'How far in advance should I book?', a: 'We recommend booking 1–2 weeks in advance for weekday events and 2–3 weeks for weekends. Peak seasons (summer, holidays) book up quickly — reserve early.' },
      { q: 'What if my event gets canceled due to weather?', a: 'We offer a full credit (no penalty) for weather-related cancellations made more than 24 hours before the event. Last-minute cancellations are subject to our standard policy.' },
    ],
    coverage: 'Major cities and surrounding metro areas statewide',
    regionNotes: 'We serve the entire state including major metro areas and surrounding suburbs.',
  }
}
